name: ihazinternet_deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_APPID}} -p ${{ secrets.AZURE_PASSWORD}} --tenant ${{ secrets.AZURE_TENANT}}
      - name: Logout
        run: |
          az logout
