name: ihazinternet_deply
on:
  workflow_dispatch:
    push:
      branches:
        - "main"
jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: latest

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_APPID}} -p ${{ secrets.AZURE_PASSWORD}} --tenant ${{ secrets.AZURE_TENANT}}
      - name: Logout
        run: |
          az logout
